server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://212.64.83.217:3306/crawler?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
        username: root
        password: houxu@900813
    thymeleaf:
        cache: false
        mode: LEGACYHTML5
        prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath:mapper/*
